In [ ]:
from sklearn import preprocessing
import pandas as pd 
import numpy as np
df = pd.read_csv("C:/Users/dell/OneDrive - Universidad de Guayaquil/Analista de datos - Linkedin Learning/base_datos_2008.csv",nrows=100000)

In [2]:
df.columns

Index(['Year', 'Month', 'DayofMonth', 'DayOfWeek', 'DepTime', 'CRSDepTime',
       'ArrTime', 'CRSArrTime', 'UniqueCarrier', 'FlightNum', 'TailNum',
       'ActualElapsedTime', 'CRSElapsedTime', 'AirTime', 'ArrDelay',
       'DepDelay', 'Origin', 'Dest', 'Distance', 'TaxiIn', 'TaxiOut',
       'Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay',
       'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay'],
      dtype='object')

In [14]:
#eliminamos los datos faltantes de las columnas que nos interesan 
df=df[["ArrDelay","DepDelay","Distance","AirTime"]].dropna()

In [15]:
df

       ArrDelay  DepDelay  Distance  AirTime
0         -14.0       8.0       810    116.0
1           2.0      19.0       810    113.0
2          14.0       8.0       515     76.0
3          -6.0      -4.0       515     78.0
4          34.0      34.0       515     77.0
...         ...       ...       ...      ...
99995     129.0     149.0       866    101.0
99996     -23.0      -2.0       866    101.0
99997      63.0      72.0       866    109.0
99998      11.0      21.0       866    102.0
99999      11.0       3.0       866    104.0

[98698 rows x 4 columns]

In [17]:
#algunos de los metodos de ml necesitan que los datos esten escalados 
#los datos escalados se centran en el cero 
x_scaled=preprocessing.scale(df)
x_scaled

array([[-0.63713243, -0.08247884,  0.40657043,  0.4452521 ],
       [-0.12045009,  0.3068154 ,  0.40657043,  0.38990966],
       [ 0.26706167, -0.08247884, -0.26709367, -0.29264705],
       ...,
       [ 1.84940134,  2.18250582,  0.53445243,  0.31611975],
       [ 0.17018373,  0.37759617,  0.53445243,  0.1869874 ],
       [ 0.17018373, -0.25943077,  0.53445243,  0.22388235]])

In [18]:
#que todas las variables esten en una misma escala es muy util por varios motivos 
x_scaled.std(axis=0)

array([1., 1., 1., 1.])

In [19]:
df.iloc[2]

ArrDelay     14.0
DepDelay      8.0
Distance    515.0
AirTime      76.0
Name: 2, dtype: float64

In [20]:
#podemos ver que tenemos los datos escalados 
#podemos ver valores por encima y debajo de la media 
x_scaled[2]

array([ 0.26706167, -0.08247884, -0.26709367, -0.29264705])

In [28]:
#vamos aplicar un escalado con minimos y maximos 
min_max_scalar= preprocessing.MinMaxScaler([0,10])
x_train_mimax=min_max_scalar.fit_transform(df)
x_train_mimax

array([[0.77199282, 0.92857143, 3.15557514, 2.91316527],
       [1.05924596, 1.125     , 3.15557514, 2.82913165],
       [1.27468582, 0.92857143, 1.85544293, 1.79271709],
       ...,
       [2.15439856, 2.07142857, 3.4023799 , 2.71708683],
       [1.22082585, 1.16071429, 3.4023799 , 2.5210084 ],
       [1.22082585, 0.83928571, 3.4023799 , 2.57703081]])

In [29]:
#transformar variables categoricas en una variable dummy 
df = pd.read_csv("C:/Users/dell/OneDrive - Universidad de Guayaquil/Analista de datos - Linkedin Learning/base_datos_2008.csv",nrows=100000)

In [30]:
pd.get_dummies(df["Origin"])

,ABQ,ALB,AMA,AUS,BDL,BFL,BHM,BNA,BOI,BTR,...,SFO,SJC,SLC,SMF,SNA,STL,SYR,TPA,TUL,TUS
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
99996,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
99997,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
99998,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
99999,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0